apiVersion: v1
kind: Service
metadata:
  name: intersection4-service
  namespace: master-rad
spec:
  selector:
    app: intersection4-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
