apiVersion: v1
kind: Service
metadata:
  name: server3-service
  namespace: master-rad
spec:
  selector:
    app: server3-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
