apiVersion: v1
kind: Service
metadata:
  name: intersection3-service
  labels:
    app: intersection3-app
spec:
  selector:
    app: intersection3-app  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 
  type: ClusterIP 
