apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-intersection4-app-to-server3-app
  namespace: master-rad
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: intersection4-app
    ports:
    - endPort: 8079
      port: 1
      protocol: TCP
  podSelector:
    matchLabels:
      app: server3-app
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-intersection4-app-to-server3-app
  namespace: master-rad
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: intersection4-app
    ports:
    - endPort: 65535
      port: 8081
      protocol: TCP
  podSelector:
    matchLabels:
      app: server3-app
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-intersection4-app-to-baza-podataka
  namespace: master-rad
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: intersection4-app
    ports:
    - endPort: 65535
      port: 1
      protocol: TCP
  podSelector:
    matchLabels:
      app: baza-podataka
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-intersection4-app-to-server2-app
  namespace: master-rad
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: intersection4-app
    ports:
    - endPort: 65535
      port: 1
      protocol: TCP
  podSelector:
    matchLabels:
      app: server2-app
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-intersection4-app-to-server-app
  namespace: master-rad
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: intersection4-app
    ports:
    - endPort: 65535
      port: 1
      protocol: TCP
  podSelector:
    matchLabels:
      app: server-app
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-intersection4-app-to-server5-app
  namespace: master-rad
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: intersection4-app
    ports:
    - endPort: 65535
      port: 1
      protocol: TCP
  podSelector:
    matchLabels:
      app: server5-app
  policyTypes:
  - Ingress
